CoPilotRoot:

<CoPilotRoot>:
    Tabs:

<HealthLabel>:
    text: 'Label'
    icon: 'error.png'
    size_hint: (None, None)
    size: ('100dp', '30dp')
    Image:
        source: root.icon
        size: ('30dp', '30dp')
    Button:
        text: root.text
        font_size: '20dp'
        on_release: root.ping("klikk")

<Tabs>:
    do_default_tab: False

    TabbedPanelItem:
        text: 'General'
        BoxLayout:
            BoxLayout:
                Label:
                    text: 'Venstre'
            BoxLayout:
                orientation: 'vertical'
                BoxLayout:
                    orientation: 'vertical'
                    Label:
                        text: '1. Det var...'
                    Label:
                        text: '1. Det var...'
                    Label:
                        text: '1. Det var...'
                BoxLayout:
                    orientation: 'vertical'
                    HealthLabel:
                        text: 'IMU'
                    Widget:


    TabbedPanelItem:
        text: 'tab2'
        BoxLayout:
            Label:
                text: 'Second tab content area'
            Button:
                text: 'Button that does nothing'
    TabbedPanelItem:
        text: 'tab3'
        RstDocument:
            text:
                '\n'.join(("Hello world", "-----------",
                "You are in the third tab."))